export const exploreRoutes = [
  'top-airing',
  'most-popular',
  'most-favorite',
  'completed',
  'recently-added',
  'recently-updated',
  'top-upcoming',
  'subbed-anime',
  'dubbed-anime',
  'movie',
  'tv',
  'ova',
  'ona',
  'special',
];

export const genres = [
  'action',
  'adventure',
  'cars',
  'comedy',
  'dementia',
  'demons',
  'drama',
  'ecchi',
  'fantasy',
  'game',
  'harem',
  'historical',
  'horror',
  'isekai',
  'josei',
  'kids',
  'magic',
  'martial arts',
  'mecha',
  'military',
  'music',
  'mystery',
  'parody',
  'police',
  'psychological',
  'romance',
  'samurai',
  'school',
  'sci-fi',
  'seinen',
  'shoujo',
  'shoujo ai',
  'shounen',
  'shounen ai',
  'slice of life',
  'space',
  'sports',
  'super power',
  'supernatural',
  'thriller',
  'vampire',
];

export const azList = [
  'all',
  'other',
  '0-9',
  'a',
  'b',
  'c',
  'd',
  'e',
  'f',
  'g',
  'h',
  'i',
  'j',
  'k',
  'l',
  'm',
  'n',
  'o',
  'p',
  'q',
  'r',
  's',
  't',
  'u',
  'v',
  'w',
  'x',
  'y',
  'z',
];
export const filterOptions = {
  type: ['all', 'movie', 'tv', 'ova', 'special', 'music'],
  status: ['all', 'finished_airing', 'currently_airing', 'not_yet_aired'],
  rated: ['all', 'g', 'pg', 'pg-13', 'r', 'r+', 'rx'],
  score: [
    'all',
    'appalling',
    'horrible',
    'very_bad',
    'bad',
    'average',
    'fine',
    'good',
    'very_good',
    'great',
    'masterpiece',
  ],
  season: ['all', 'spring', 'summer', 'fall', 'winter'],
  language: ['all', 'sub', 'dub', 'sub_dub'],
  sort: [
    'default',
    'recently_added',
    'recently_updated',
    'score',
    'name_az',
    'release_date',
    'most_watched',
  ],
  // index 11,32,33 are empty because of  missing data-id by hianime
  genres: [
    'action',
    'adventure',
    'cars',
    'comedy',
    'dementia',
    'demons',
    'mystery',
    'drama',
    'ecchi',
    'fantasy',
    'game',
    '',
    'historical',
    'horror',
    'kids',
    'magic',
    'martial_arts',
    'mecha',
    'music',
    'parody',
    'samurai',
    'romance',
    'school',
    'sci-fi',
    'shoujo',
    'shoujo_ai',
    'shounen',
    'shounen_ai',
    'space',
    'sports',
    'super_power',
    'vampire',
    '',
    '',
    'harem',
    'slice_of_life',
    'supernatural',
    'military',
    'police',
    'psychological',
    'thriller',
    'seinen',
    'josei',
    'isekai',
  ],
};
